- '173507340883066880' # dankat#2959 (Charles Zhang)
- '302921509763022889' # Picowchew#1559 (Picowchew The Panda)
- '688101791656575077' # fishyfishyfish#4962 (Mark Chen)
- '255088818309300235' # ǝʞıɹʇSǝldıɹ⊥#9999 (Alex Zhang)
- '297185799584350208' # u rod#0019 (Chris Xie)
- '750744296684126289' # elaine#2156 (Elaine Han)
- '220283093804646400' # android#0456 (Andrew Wang)
- '183383084538789888' # SurgeonInASuit#1579 (Edwin Yang)
- '522588708931764243' # mcpenguin#6194 (Marcus Chan)
- '159284335973761024' # Scout#9630 (Victor Zheng)
- '191625275551776769' # Caillou#4179 (Allen Lu)
- '843279881260761108' # gnishi#2067 (Gen Nishiwaki)